### ISSUE TITLE
Junior Scum Masters & Helpers Create Qualtrics Survey Draft

### ISSUE THREAD

**Issue by kaylynott** [kaylynott/QMB-210-Group#1]
Please have this done by our next scrum meeting, which will happen at the end of this please!

**Comment by peytonmeiring** [comment]
https://utampa.az1.qualtrics.com/jfe/preview/previewId/4a28fdc0-32e3-410f-9fb8-11aa16bae46d/SV_9sIxt4u9X63tVfo?Q_CHL=preview&Q_SurveyVersionID=current

**Comment by nicawaz** [comment]
Completed the assignment

**Comment by PiperRandall** [comment]
done
